openapi: 3.1.0
info:
  version: 1.0.0
  title: MarketPlace app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of MarketPlace app
tags:
  - name: Auth
    description: Auth operations.
  - name: Products
    description: Operations about product.
  - name: Favorites
    description: Operations about favorites.
  - name: User
    description: Operations about user.
  - name: Reviews
    description: Operations about reviews.
servers:
  - url: https://marketplace-backend-vrwj.onrender.com
  - url: http://localhost:3000
paths:
  /auth/register:
    post:
      $ref: ../swagger/path/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/path/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/path/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/path/auth/logout.yaml
  /products:
    get:
      $ref: ../swagger/path/products/get.yaml
    post:
      $ref: '../swagger/path/products/post.yaml'
  /products/{productId}:
    get:
      $ref: ../swagger/path/products/{id}/get.yaml
    patch:
      $ref: ../swagger/path/products/{id}/patch.yaml
    delete:
      $ref: ../swagger/path/products/{id}/delete.yaml
  /favorites:
    get:
      $ref: '../swagger/path/favorites/get.yaml'
  /favorites/{productId}:
    post:
      $ref: '../swagger/path/favorites/{id}/post.yaml'
    delete:
      $ref: '../swagger/path/favorites/{id}/delete.yaml'
  /user/{userId}:
    get:
      $ref: '../swagger/path/user/{id}/get.yaml'
    patch:
      $ref: '../swagger/path/user/{id}/patch.yaml'
  /reviews/{sellerId}:
    get:
      $ref: '../swagger/path/review/{id}/get.yaml'
    post:
      $ref: '../swagger/path/review/{id}/post.yaml'
  /reviews/{sellerId}/stats:
    get:
      $ref: '../swagger/path/review/{id}/stats/get.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
