openapi: 3.1.0
info:
  version: 1.0.0
  title: MarketPlace app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of MarketPlace app
tags:
  - name: Auth
    description: Auth operations.
  - name: Product
    description: Operations about product.
  - name: User
    description: Operations about user.
servers:
  # - url: https://.onrender.com
  - url: http://localhost:3000
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/path/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  # /user:
  #   get:
  #     $ref: '../swagger/paths/user/get.yaml'
  #   patch:
  #     $ref: '../swagger/paths/user/patch.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
