type: object
required:
  - name
  - category
  - description
  - condition
  - price
  - phoneNumber
  - photo
  - region
  - city
  - delivery
properties:
  name:
    description: Name of product
    type: string
  category:
    description: Category product belongs to
    type: string
    enum:
      - children
      - pet
      - home
      - fashion
      - hobby
      - sport
      - tools
      - gadget
      - garden
      - free
  description:
    description: Description of the product
    type: string
  condition:
    description: Is it new or used
    type: string
    enum:
      - new
      - used
  price:
    description: The price for the product
    type: number
  phoneNumber:
    description: Phone number of the seller
    type: string
  photo:
    description: Link to the photo of the product
    type: string
    format: uri
  region:
    description: Please select one of 25 regions of Ukraine
    type: string
    enum:
      - Vinnytska
      - Volynska
      - Dnipropetrovska
      - Donetska
      - Zhytomyrska
      - Zakarpatska
      - Zaporizka
      - Ivano-Frankivska
      - Kyivska
      - Kirovohradska
      - Luhanska
      - Lvivska
      - Mykolaivska
      - Odeska
      - Poltavska
      - Rivnenska
      - Sumska
      - Ternopilska
      - Kharkivska
      - Khersonska
      - Khmelnytska
      - Cherkaska
      - Chernivetska
      - Chernihivska
      - Crimea
  city:
    description: Type the city
    type: string
  delivery:
    description: Select what delivery you can provide
    type: string
    enum:
      - selfPickup
      - mail
